#!/bin/sh

touch /etc/config/simple-xray
uci set simple-xray.config=simple-xray
uci set simple-xray.config.enabled='0'
uci set simple-xray.config.config_file='/etc/xray/config.json'
uci commit simple-xray

mkdir -p /var/log/xray
touch /var/log/xray/error.log

return 0